/**
 * Generic validation for ALL captured scenarios (live-capture evidence tier).
 * Every scenario generated by log-capture-converter must:
 *  - resolve without dangling {{placeholders}}
 *  - never contain literal credentials (password must be [REDACTED])
 *  - have every client-initiated exchange matchable via RdoMock without
 *    crossing members
 *  - keep pushOnly exchanges out of request matching
 *
 * Add each new captured scenario to the CAPTURED list below — scenario-specific
 * protocol-order assertions (like login-full's) belong in their own test file.
 */

import { describe, it, expect } from '@jest/globals';
import type { RdoScenario } from '../../types/rdo-exchange-types';
import { RdoMock } from '../../rdo-mock';
import { resolveScenarioVariables } from '../../log-capture-converter';
import { loginFullCapturedScenario } from './login-full-captured.scenario';
import { chatCapturedScenario } from './chat-captured.scenario';
import { mailReadCapturedScenario } from './mail-read-captured.scenario';
import { panelsTourCapturedScenario } from './panels-tour-captured.scenario';
import { roadBuildRejectedCapturedScenario } from './road-build-rejected-captured.scenario';
import { construireCapturedScenario } from './construire-captured.scenario';
import { parcoursEnchaineCapturedScenario } from './parcours-enchaine-captured.scenario';
import { communicationCapturedScenario } from './communication-captured.scenario';
import { servicePublicCapturedScenario } from './service-public-captured.scenario';
import { derniersMembresCapturedScenario } from './derniers-membres-captured.scenario';

const CAPTURED: RdoScenario[] = [
  loginFullCapturedScenario,
  chatCapturedScenario,
  mailReadCapturedScenario,
  panelsTourCapturedScenario,
  roadBuildRejectedCapturedScenario,
  construireCapturedScenario,
  parcoursEnchaineCapturedScenario,
  communicationCapturedScenario,
  servicePublicCapturedScenario,
  derniersMembresCapturedScenario,
];

describe.each(CAPTURED.map(s => [s.name, s] as const))(
  'captured scenario: %s',
  (_name, scenario) => {
    const resolved = resolveScenarioVariables(scenario);
    const requests = resolved.exchanges.filter(e => !e.pushOnly && e.request !== '');

    it('has exchanges and resolves without dangling placeholders', () => {
      expect(scenario.exchanges.length).toBeGreaterThan(0);
      expect(JSON.stringify(resolved.exchanges)).not.toContain('{{');
    });

    it('never contains literal credentials', () => {
      const source = JSON.stringify(scenario.exchanges);
      expect(source).not.toMatch(/"%test3"/);
      expect(scenario.variables.password).toBe('[REDACTED]');
    });

    it('every client-initiated exchange is matchable without crossing members', () => {
      const mock = new RdoMock();
      mock.addScenario(resolved);
      const problems: string[] = [];
      for (const exchange of requests) {
        const result = mock.match(exchange.request);
        if (!result) {
          problems.push(`unmatched: ${exchange.id}`);
          continue;
        }
        if (
          exchange.matchKeys?.member &&
          result.exchange.matchKeys?.member !== exchange.matchKeys.member
        ) {
          problems.push(`crossed member: ${exchange.id} → ${result.exchange.id}`);
        }
      }
      expect(problems).toEqual([]);
    });

    it('pushOnly exchanges are excluded from request matching', () => {
      const mock = new RdoMock();
      mock.addScenario(resolved);
      for (const p of resolved.exchanges.filter(e => e.pushOnly)) {
        const result = mock.match(p.response);
        expect(result?.exchange.pushOnly ?? false).toBe(false);
      }
    });
  }
);
