export { TownsTab } from './TownsTab';
export { MinistriesTab } from './MinistriesTab';
export { JobsTab } from './JobsTab';
export { ResidentialsTab } from './ResidentialsTab';
export { VotesTab } from './VotesTab';
export { RatingsTab } from './RatingsTab';
export { OverviewSection } from './OverviewSection';
export { AdministrationSection } from './AdministrationSection';
export { DemographicsSection } from './DemographicsSection';
export { ElectionsSection } from './ElectionsSection';
export { buildCivicTabs, getGeneralGroupId, isCapitolBuilding } from './CivicTabConfig';
export type { CivicTabId } from './CivicTabConfig';
